### PR TITLE
Dynreconf

### PR DESCRIPTION
**Pull request by asmodehn**

### CODE REVIEW

**Comment by AlexReimann** [comment]
Should add that the default value comes from a parameter file.
You don't want to change the msg package to change the default / start value

**Comment by asmodehn** [comment]
Not sure how I would do that...
I also don't want the "generic" config to depend on a specific node implementation...

Also in the code I get the ros param before setting up the dynamic reconfigure, which mean the default value in the dynamic reconfigure file is ignored... I think...

**Comment by AlexReimann** [comment]
Yeah that's correct. But nothing sets the ros param for that parameter (besides the dyn. reconfigure) or am I missing something?

**Comment by asmodehn** [comment]
I am using the hardcoded default value in the ros1_pytemplate.Fibonacci
class...
But I see your point and I agree : it would be clearer if it was in the
yaml param file at the beginning and used.
But then I get two default values, and only one gets used (the
dyn-configure one is ignored)

Is there a way to set the dynamic reconfigure default value to the one in
the yaml ?
From the documentation, I read it is the opposite ( dynamic reconf default
value will erase the one set in rosparams - which I think makes things less
obvious) ?

--
AlexV

**Comment by AlexReimann** [comment]
Documentation is wrong then. It uses the dynamic reconfigure default only if there is no parameter on the ros parameter server yet. 

At least in c++ .. maybe test it?

**Comment by asmodehn** [comment]
Ah I remember talking about this with Dan, and testing this stuff two years ago... I guess I was led astray again because of https://answers.ros.org/question/28327/dynamic-reconfigure-default-parameters/

**Comment by asmodehn** [comment]
so you meant like this ?

**Pull request merged**
